name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Replace 'main' with your branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Use the version you need

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACCESS_TOKEN }} # Replace with your GitHub access token
          publish_dir: ./dist # Path to the build output directory
          publish_branch: gh-pages # Branch to deploy to
          force_orphan: true # Create an orphan branch if necessary